/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphFrame.java
 *
 * Created on 19/07/2011, 18:08:29
 */

package fronteira.principal;

import java.awt.Color;
/*import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;*/
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/*import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.border.Border;*/
import javax.swing.border.LineBorder;

import controle.Workspace;
//import fronteira.GraphFilter;

/**
 *
 * @author pesquisador
 */
@SuppressWarnings("serial")
public class JanelaPrincipal extends javax.swing.JFrame {
	
    /** Creates new form GraphFrame */
    public JanelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	setAreaDesenho();
    	
    	
    	//Janela sobre
        janelaSobre = new javax.swing.JFrame();
        panelSobre = new javax.swing.JPanel();
        conteudoSobre = new javax.swing.JScrollPane();
        textoSobre = new javax.swing.JTextArea();
        btnOkSobre = new javax.swing.JButton();
        logoGraphGSobre = new javax.swing.JLabel();
        
        //Painel Principal
        principalPanel = new javax.swing.JPanel();
        
        //Barra de desenho
        draw_toolBar = new javax.swing.JToolBar();
        btnDesenharSelecionar = new javax.swing.JToggleButton();
        btnDesenharDeletar = new javax.swing.JToggleButton();
        btnDesenharRetangulo = new javax.swing.JToggleButton();
        btnDesenharVertice = new javax.swing.JToggleButton();
        btnDesenharReta = new javax.swing.JToggleButton();
        
        
        anotacoesPanel = new javax.swing.JScrollPane();
        anotacoesTextArea = new javax.swing.JTextArea();
        anotacoesLabel = new javax.swing.JLabel();
        
        //Barra de ferramentas
        toolBar = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        separadorCopiarColar = new javax.swing.JToolBar.Separator();
        btnCopiar = new javax.swing.JButton();
        btnColar = new javax.swing.JButton();
        separadorExportar = new javax.swing.JToolBar.Separator();
        btnExportar = new javax.swing.JButton();
        
        //
        
        //areaDesenhoScroll = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemNovo = new javax.swing.JMenuItem();
        itemAbrir = new javax.swing.JMenuItem();
        itemSalvar = new javax.swing.JMenuItem();
        separadorMenuArquivo1 = new javax.swing.JPopupMenu.Separator();
        itemExportar = new javax.swing.JMenuItem();
        separadorMenuArquivo2 = new javax.swing.JPopupMenu.Separator();
        itemSair = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        itemDesfazer = new javax.swing.JMenuItem();
        itemRefazer = new javax.swing.JMenuItem();
        separadorMenuEditar = new javax.swing.JPopupMenu.Separator();
        itemCopiar = new javax.swing.JMenuItem();
        itemColar = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        menuInserir = new javax.swing.JMenu();
        itemInserirCirculo = new javax.swing.JMenuItem();
        itemInserirReta = new javax.swing.JMenuItem();
        separadorMenuFerramentas = new javax.swing.JPopupMenu.Separator();
        menuAjuda = new javax.swing.JMenu();
        itemTutorial = new javax.swing.JMenuItem();
        separadorMenuAjuda = new javax.swing.JPopupMenu.Separator();
        menuItemSobre = new javax.swing.JMenuItem();

        janelaSobre.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        janelaSobre.setTitle("Sobre");
        janelaSobre.setName("janelaSobre"); // NOI18N
        janelaSobre.setResizable(false);

        textoSobre.setColumns(20);
        textoSobre.setEditable(false);
        textoSobre.setLineWrap(true);
        textoSobre.setRows(5);
        textoSobre.setText("Software criado como projeto final da disciplina\nEngenharia de Software 2\n\nProfessor: \nJucimar Jr\n\nAlunos:\nÍgor Jacaúna\nJosiane Rodrigues\nLídia Lizziane\nRodrigo Bernardino\nWilliam Belleza");
        conteudoSobre.setViewportView(textoSobre);

        btnOkSobre.setText("Ok!");
        btnOkSobre.setToolTipText("Clique para fechar esta janela");
        btnOkSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkSobreActionPerformed(evt);
            }
        });

        logoGraphGSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/graphG.png"))); // NOI18N

        javax.swing.GroupLayout panelSobreLayout = new javax.swing.GroupLayout(panelSobre);
        panelSobre.setLayout(panelSobreLayout);
        panelSobreLayout.setHorizontalGroup(
            panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSobreLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(logoGraphGSobre)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(panelSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conteudoSobre, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSobreLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(btnOkSobre)
                .addGap(168, 168, 168))
        );
        panelSobreLayout.setVerticalGroup(
            panelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoGraphGSobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conteudoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOkSobre)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout janelaSobreLayout = new javax.swing.GroupLayout(janelaSobre.getContentPane());
        janelaSobre.getContentPane().setLayout(janelaSobreLayout);
        janelaSobreLayout.setHorizontalGroup(
            janelaSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        janelaSobreLayout.setVerticalGroup(
            janelaSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        janelaSobre.getAccessibleContext().setAccessibleParent(panelSobre);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GraphG");
        setName("framePrincipal"); // NOI18N
        
        /**--------------Inicio da barra de desenho---------------**/
        draw_toolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        draw_toolBar.setFloatable(false);
        draw_toolBar.setOrientation(1);
        draw_toolBar.setRollover(true);

        btnDesenharSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/cursor.png"))); // NOI18N
        btnDesenharSelecionar.setFocusable(false);
        btnDesenharSelecionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesenharSelecionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        draw_toolBar.add(btnDesenharSelecionar);
        btnDesenharSelecionar.setSelected(true);
        
        btnDesenharDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/deletar.png"))); // NOI18N
        btnDesenharDeletar.setFocusable(false);
        btnDesenharDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesenharDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        draw_toolBar.add(btnDesenharDeletar);
        
        btnDesenharRetangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/retangulo.png"))); // NOI18N
        btnDesenharRetangulo.setFocusable(false);
        btnDesenharRetangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesenharRetangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        draw_toolBar.add(btnDesenharRetangulo);
        
        btnDesenharVertice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/circulo.png"))); // NOI18N
        btnDesenharVertice.setFocusable(false);
        btnDesenharVertice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesenharVertice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        draw_toolBar.add(btnDesenharVertice);

        btnDesenharReta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/reta.png"))); // NOI18N
        btnDesenharReta.setFocusable(false);
        btnDesenharReta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesenharReta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        draw_toolBar.add(btnDesenharReta);
        
        btnDesenharSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnDesenharRetangulo.setSelected(false);
            	btnDesenharSelecionar.setSelected(true);
            	btnDesenharDeletar.setSelected(false);
            	btnDesenharVertice.setSelected(false);
            	btnDesenharReta.setSelected(false);
            	btnDesenharSelecionarActionPerformed(evt);
            }
        });
        
        btnDesenharDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnDesenharRetangulo.setSelected(false);
            	btnDesenharSelecionar.setSelected(false);
            	btnDesenharDeletar.setSelected(true);
            	btnDesenharVertice.setSelected(false);
            	btnDesenharReta.setSelected(false);
            	btnDesenharDeletarActionPerformed(evt);
            }
        });
        
        btnDesenharRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnDesenharRetangulo.setSelected(true);
            	btnDesenharDeletar.setSelected(false);
            	btnDesenharVertice.setSelected(false);
            	btnDesenharSelecionar.setSelected(false);
            	btnDesenharReta.setSelected(false);
            	btnDesenharRetanguloActionPerformed(evt);
            }
        });
        
        btnDesenharVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnDesenharRetangulo.setSelected(false);
            	btnDesenharDeletar.setSelected(false);
            	btnDesenharVertice.setSelected(true);
            	btnDesenharSelecionar.setSelected(false);
            	btnDesenharReta.setSelected(false);
            	btnDesenharVerticeActionPerformed(evt);
            }
        });
        
        btnDesenharReta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnDesenharRetangulo.setSelected(false);
            	btnDesenharDeletar.setSelected(false);
            	btnDesenharReta.setSelected(true);
            	btnDesenharVertice.setSelected(false);
            	btnDesenharSelecionar.setSelected(false);
                btnDesenharRetaActionPerformed(evt);
            }
        });
        
/**--------------Fim da barra de desenho---------------**/
        
        anotacoesTextArea.setColumns(20);
        anotacoesTextArea.setLineWrap(true);
        anotacoesTextArea.setRows(5);
        anotacoesTextArea.setToolTipText("Escreva aqui algo importante sobreo grafo a ser desenhado");
        anotacoesPanel.setViewportView(anotacoesTextArea);

        anotacoesLabel.setText("Anotações");

        toolBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.setBorderPainted(false);
        toolBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolBar.setMargin(new java.awt.Insets(20, 20, 20, 20));
        toolBar.setName("Barra de ferramentas"); // NOI18N

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/novo.png"))); // NOI18N
        btnNovo.setToolTipText("Criar um novo arquivo");
        btnNovo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	novoActionPerformed(evt);
            }
        });
        toolBar.add(btnNovo);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/abrir.png"))); // NOI18N
        btnAbrir.setToolTipText("Abrir um arquivo");
        btnAbrir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        toolBar.add(btnAbrir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar um arquivo");
        btnSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        toolBar.add(btnSalvar);
        toolBar.add(separadorCopiarColar);

        btnCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/copiar.png"))); // NOI18N
        btnCopiar.setToolTipText("Copiar");
        btnCopiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCopiar.setFocusable(false);
        btnCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnCopiar);

        btnColar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/colar.png"))); // NOI18N
        btnColar.setToolTipText("Colar");
        btnColar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnColar.setFocusable(false);
        btnColar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnColar);
        toolBar.add(separadorExportar);

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/images/exportar.png"))); // NOI18N
        btnExportar.setToolTipText("Exportar para .DOT");
        btnExportar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExportar.setFocusable(false);
        btnExportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });
        toolBar.add(btnExportar);

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(anotacoesLabel)
                .addContainerGap(933, Short.MAX_VALUE))
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addComponent(draw_toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelGraf, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                    .addComponent(anotacoesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE))
                .addContainerGap())
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(draw_toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelGraf, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anotacoesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anotacoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuArquivo.setText("Arquivo");

        itemNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        itemNovo.setText("Novo");
        itemNovo.setToolTipText("Criar um novo arquivo");
        itemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        menuArquivo.add(itemNovo);

        itemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemAbrir.setText("Abrir");
        itemAbrir.setToolTipText("Salvar arquivo");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        menuArquivo.add(itemAbrir);

        itemSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemSalvar.setText("Salvar");
        itemSalvar.setToolTipText("Exportar grafo para .DOT");
        itemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        menuArquivo.add(itemSalvar);
        menuArquivo.add(separadorMenuArquivo1);

        itemExportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itemExportar.setText("Exportar");
        itemExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });
        menuArquivo.add(itemExportar);

        separadorMenuArquivo2.setToolTipText("Abrir um arquivo");
        menuArquivo.add(separadorMenuArquivo2);

        itemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itemSair.setText("Sair");
        itemSair.setToolTipText("Sair do programa");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemSair);

        menuBar.add(menuArquivo);

        menuEditar.setText("Editar");

        itemDesfazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        itemDesfazer.setText("Desfazer");
        menuEditar.add(itemDesfazer);

        itemRefazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemRefazer.setText("Refazer");
        menuEditar.add(itemRefazer);
        menuEditar.add(separadorMenuEditar);

        itemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemCopiar.setText("Copiar");
        menuEditar.add(itemCopiar);

        itemColar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        itemColar.setText("Colar");
        menuEditar.add(itemColar);

        menuBar.add(menuEditar);

        menuFerramentas.setText("Ferramentas");

        menuInserir.setText("Inserir");

        itemInserirCirculo.setText("Círculo");
        menuInserir.add(itemInserirCirculo);

        itemInserirReta.setText("Reta");
        menuInserir.add(itemInserirReta);

        menuFerramentas.add(menuInserir);
        menuFerramentas.add(separadorMenuFerramentas);

        menuBar.add(menuFerramentas);

        menuAjuda.setText("Ajuda");

        itemTutorial.setText("Tutorial");
        itemTutorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1,0));
        itemTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTutorialActionPerformed(evt);
            }
        });
        menuAjuda.add(itemTutorial);
        menuAjuda.add(separadorMenuAjuda);

        menuItemSobre.setText("Sobre");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuItemSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("GraphG 1.0");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**------Ações dos botões da barra de ferramentas---------**/
    private void novoActionPerformed(java.awt.event.ActionEvent evt){
    	int opcao = 0;
    	if(!workspace.isSaved()){
    		opcao = JOptionPane.showConfirmDialog(null,"Você não salvou as alterações, tem certeza de que quer criar um novo arquivo?", "Novo arquivo?", JOptionPane.YES_NO_OPTION);
    		if(opcao==0){
    			workspace.resetWorkspace();
    			anotacoesTextArea.setText("");
    		}
    	}else{
    		workspace.resetWorkspace();
    		anotacoesTextArea.setText("");
    	}
    }
    
    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new GraphFilter());
		jfc.setAcceptAllFileFilterUsed(false);
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
    		File file = jfc.getSelectedFile();
    		abrir(file);
    	}
    }

    private void abrir(File file){
		workspace.open(file.getName(), file.getPath(), painelGraf);
		anotacoesTextArea.setText(workspace.getAnotacoes());
   }   
    
    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser jfs = new JFileChooser();
        jfs.setFileFilter(new GraphFilter());
        jfs.setAcceptAllFileFilterUsed(false);
        	if(jfs.showDialog(this, "Exportar") == JFileChooser.APPROVE_OPTION) {
        		File file = jfs.getSelectedFile();
        		workspace.exportar(file.getPath());
        	}
    }
    
    
    /**------Ações dos itens do menu---------**/

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {
       janelaSobre.setVisible(true);
       janelaSobre.setSize(400 , 370);
    }

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new GraphFilter());
		jfc.setAcceptAllFileFilterUsed(false);
        	if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        		File file = jfc.getSelectedFile();
        		abrir(file);
        	}
    }

    
    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser jfs = new JFileChooser();
        jfs.setFileFilter(new GraphFilter());
        jfs.setAcceptAllFileFilterUsed(false);
        	if(jfs.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        		File file = jfs.getSelectedFile();
        		anotacoes = anotacoesTextArea.getText(); 
        		workspace.salvar(file.getName(), file.getPath(),anotacoes);
        }
    }
    
    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    
    }
    
    /**------Ações dos botões da barra de desenho---------**/
        
    private void btnDesenharSelecionarActionPerformed(java.awt.event.ActionEvent evt) {
        workspace.setState(Workspace.STATE_SELECAO);
    }
    
    private void btnDesenharDeletarActionPerformed(java.awt.event.ActionEvent evt) {
        workspace.setState(Workspace.STATE_DELETAR);
    }
    
    private void btnDesenharRetanguloActionPerformed(java.awt.event.ActionEvent evt) {
        workspace.setState(Workspace.STATE_DESENHA_VERTICE_R);
    }
    
    private void btnDesenharVerticeActionPerformed(java.awt.event.ActionEvent evt) {
        workspace.setState(Workspace.STATE_DESENHA_VERTICE_C);
    }
    
    private void btnDesenharRetaActionPerformed(java.awt.event.ActionEvent evt) {
        workspace.setState(Workspace.STATE_DESENHA_ARESTA);
    }
    
    public void setAreaDesenho(){
    	painelGraf.setBackground(Color.WHITE);
    	painelGraf.setBorder(new LineBorder(Color.DARK_GRAY));
    	
    }
    
    private void btnOkSobreActionPerformed(java.awt.event.ActionEvent evt) {
        janelaSobre.dispose();        
    }
    
    private void itemTutorialActionPerformed(java.awt.event.ActionEvent evt) {
        Tutorial tuto = new Tutorial();
        tuto.montarTuto();
    }
    
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anotacoesLabel;
    private javax.swing.JScrollPane anotacoesPanel;
    private javax.swing.JTextArea anotacoesTextArea;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnColar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JToolBar draw_toolBar;
    private javax.swing.JMenuItem itemInserirCirculo;
    private javax.swing.JMenuItem itemInserirReta;
    private javax.swing.JButton btnOkSobre;
    private javax.swing.JLabel logoGraphGSobre;
    private javax.swing.JMenuItem itemNovo;
    private javax.swing.JMenuItem itemDesfazer;
    private javax.swing.JMenuItem itemRefazer;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemSalvar;
    private javax.swing.JMenuItem itemExportar;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemCopiar;
    private javax.swing.JMenuItem itemColar;
    private javax.swing.JPanel panelSobre;
    // TODO private JPanel areaDesenhoScroll;
    private javax.swing.JScrollPane conteudoSobre;
    private javax.swing.JPopupMenu.Separator separadorMenuArquivo1;
    private javax.swing.JPopupMenu.Separator separadorMenuArquivo2;
    private javax.swing.JPopupMenu.Separator separadorMenuAjuda;
    private javax.swing.JPopupMenu.Separator separadorMenuEditar;
    private javax.swing.JPopupMenu.Separator separadorMenuFerramentas;
    private javax.swing.JToolBar.Separator separadorCopiarColar;
    private javax.swing.JToolBar.Separator separadorExportar;
    private javax.swing.JTextArea textoSobre;
    private javax.swing.JToggleButton btnDesenharSelecionar;
    private javax.swing.JToggleButton btnDesenharDeletar;
    private javax.swing.JToggleButton btnDesenharRetangulo;
    private javax.swing.JToggleButton btnDesenharVertice;
    private javax.swing.JToggleButton btnDesenharReta;
    private javax.swing.JFrame janelaSobre;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuInserir;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JMenuItem itemTutorial;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JToolBar toolBar;
    private fronteira.desenho.PainelGraficos painelGraf = new fronteira.desenho.PainelGraficos();
    private controle.Workspace workspace = new controle.Workspace(painelGraf);
	private String anotacoes = new String();
    // End of variables declaration//GEN-END:variables

}
